[2023-05-31T02:39:38.688+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:39:35.202608+00:00 [queued]>
[2023-05-31T02:39:38.700+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:39:35.202608+00:00 [queued]>
[2023-05-31T02:39:38.700+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:39:38.701+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-05-31T02:39:38.701+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:39:38.720+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): created_folders_task> on 2023-05-31 02:39:35.202608+00:00
[2023-05-31T02:39:38.728+0000] {standard_task_runner.py:55} INFO - Started process 656 to run task
[2023-05-31T02:39:38.731+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'captura_dados', 'created_folders_task', 'manual__2023-05-31T02:39:35.202608+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/captura_dados.py', '--cfg-path', '/tmp/tmpexdke82u']
[2023-05-31T02:39:38.734+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask created_folders_task
[2023-05-31T02:39:38.802+0000] {task_command.py:388} INFO - Running <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:39:35.202608+00:00 [running]> on host bbf89157dbab
[2023-05-31T02:39:38.892+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=captura_dados
AIRFLOW_CTX_TASK_ID=created_folders_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T02:39:35.202608+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T02:39:35.202608+00:00
[2023-05-31T02:39:38.898+0000] {logging_mixin.py:137} INFO - O diretório engineer já existe.
[2023-05-31T02:39:38.898+0000] {logging_mixin.py:137} INFO - /opt/***/***-docker/data/engineer
[2023-05-31T02:39:38.898+0000] {logging_mixin.py:137} INFO - O diretório raw já existe.
[2023-05-31T02:39:38.898+0000] {logging_mixin.py:137} INFO - /opt/***/***-docker/data/raw
[2023-05-31T02:39:38.898+0000] {logging_mixin.py:137} INFO - O diretório refined já existe.
[2023-05-31T02:39:38.899+0000] {logging_mixin.py:137} INFO - /opt/***/***-docker/data/refined
[2023-05-31T02:39:38.899+0000] {logging_mixin.py:137} INFO - O diretório transient já existe.
[2023-05-31T02:39:38.899+0000] {logging_mixin.py:137} INFO - /opt/***/***-docker/data/transient
[2023-05-31T02:39:38.899+0000] {logging_mixin.py:137} INFO - O diretório trusted já existe.
[2023-05-31T02:39:38.899+0000] {logging_mixin.py:137} INFO - /opt/***/***-docker/data/trusted
[2023-05-31T02:39:38.899+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-31T02:39:38.909+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=captura_dados, task_id=created_folders_task, execution_date=20230531T023935, start_date=20230531T023938, end_date=20230531T023938
[2023-05-31T02:39:38.942+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-05-31T02:39:38.969+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
